apps/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'apps.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^dogs/', include('dogs.urls', namespace='dogs')),
    url(r'^cats/', include('cats.urls', namespace='cats')),
    url(r'^owners/', include('owners.urls', namespace='owners')),
    url(r'^$', 'cats.views.home'),
]

cats/urls.py
from django.conf.urls import patterns, url

from cats import views

urlpatterns = patterns('',
  url(r'^$', views.cats_list, name='cats_list'),
  url(r'^new$', views.cats_create, name='cats_new'),
  url(r'^edit/(?P<pk>\d+)$', views.cats_update, name='cats_edit'),
  url(r'^delete/(?P<pk>\d+)$', views.cats_delete, name='cats_delete'),
)

dogs/urls.py
from django.conf.urls import patterns, url

from dogs import views

urlpatterns = patterns('',
  url(r'^$', views.dogsList.as_view(), name='dogs_list'),
  url(r'^new$', views.dogsCreate.as_view(), name='dogs_new'),
  url(r'^edit/(?P<pk>\d+)$', views.dogsUpdate.as_view(), name='dogs_edit'),
  url(r'^delete/(?P<pk>\d+)$', views.dogsDelete.as_view(), name='dogs_delete'),
)

owners/urls.py
from django.conf.urls import patterns, url

from owners import views

urlpatterns = patterns('',
  url(r'^$', views.owners_list, name='owners_list'),
  url(r'^new$', views.owners_create, name='owners_new'),
  url(r'^edit/(?P<pk>\d+)$', views.owners_update, name='owners_edit'),
  url(r'^delete/(?P<pk>\d+)$', views.owners_delete, name='owners_delete'),
)

cats/models.py
from django.db import models
from django.core.urlresolvers import reverse


class cats(models.Model):
    name = models.CharField(max_length=200)
    date = models.DateField()

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('cats:cats_edit', kwargs={'pk': self.pk})

dogs/models.py
from django.db import models
from django.core.urlresolvers import reverse


class dogs(models.Model):
    name = models.CharField(max_length=200)
    date = models.DateField()

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('dogs:dogs_edit', kwargs={'pk': self.pk})

owners/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.conf import settings

class owners(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    name = models.CharField(max_length=200)
    date = models.DateField()

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('owners:owners_edit', kwargs={'pk': self.pk})

apps/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse

def home(request, template_name='apps/home.html'):
    return render(request, template_name)

cats/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.forms import ModelForm

from cats.models import cats

class catsForm(ModelForm):
    class Meta:
        model = cats
        fields = ['name', 'date']

def home(request, template_name='cats/menu.html'):
    return render(request, template_name)

def cats_list(request, template_name='cats/cats_list.html'):
    cat = cats.objects.all()
    data = {}
    data['object_list'] = cat
    return render(request, template_name, data)

def cats_create(request, template_name='cats/cats_form.html'):
    form = catsForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('cats:cats_list')
    return render(request, template_name, {'form':form})

def cats_update(request, pk, template_name='cats/cats_form.html'):
    cat= get_object_or_404(cats, pk=pk)
    form = catsForm(request.POST or None, instance=cat)
    if form.is_valid():
        form.save()
        return redirect('cats:cats_list')
    return render(request, template_name, {'form':form})

def cats_delete(request, pk, template_name='cats/cats_confirm_delete.html'):
    cat= get_object_or_404(cats, pk=pk)
    if request.method=='POST':
        cat.delete()
        return redirect('cats:cats_list')
    return render(request, template_name, {'object':cats})

dogs/views.py
from django.http import HttpResponse
from django.views.generic import TemplateView,ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy

from dogs.models import dogs

class dogsList(ListView):
    model = dogs

class dogsCreate(CreateView):
    model = dogs
    fields = ['name', 'date']
    success_url = reverse_lazy('dogs:dogs_list')

class dogsUpdate(UpdateView):
    model = dogs
    fields = ['name', 'date']
    success_url = reverse_lazy('dogs:dogs_list')

class dogsDelete(DeleteView):
    model = dogs
    success_url = reverse_lazy('dogs:dogs_list')

owners/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.forms import ModelForm

from owners.models import owners

class ownersForm(ModelForm):
    class Meta:
        model = owners
        fields = ['name', 'date']

@login_required
def owners_list(request, template_name='owners/owners_list.html'):
    if request.user.is_superuser:
        owner = owners.objects.all()
    else:
        owner = owners.objects.filter(user=request.user)
    data = {}
    data['object_list'] = owner
    return render(request, template_name, data)

@login_required
def owners_create(request, template_name='owners/owners_form.html'):
    form = ownersForm(request.POST or None)
    if form.is_valid():
        owners = form.save(commit=False)
        owners.user = request.user
        owners.save()
        return redirect('owners:owners_list')
    return render(request, template_name, {'form':form})

@login_required
def owners_update(request, pk, template_name='owners/owners_form.html'):
    if request.user.is_superuser:
        owner= get_object_or_404(owners, pk=pk)
    else:
        owner= get_object_or_404(owners, pk=pk, user=request.user)
    form = ownersForm(request.POST or None, instance=owner)
    if form.is_valid():
        form.save()
        return redirect('owners:owners_list')
    return render(request, template_name, {'form':form})

@login_required
def owners_delete(request, pk, template_name='owners/dogs_confirm_delete.html'):
    if request.user.is_superuser:
        owner= get_object_or_404(owners, pk=pk)
    else:
        owner= get_object_or_404(owners, pk=pk, user=request.user)
    if request.method=='POST':
        owner.delete()
        return redirect('owners:owners_list')
    return render(request, template_name, {'object':owners})

cats/templates/cats/cats_confirm_delete.html
{% extends 'cats/home.html' %}

{% block title %}Cats{% endblock %}

{% block content %}
<form method="post">{% csrf_token %}
    Are you sure you want to delete  ?
    <input type="submit" value="Submit" />
</form>
{% endblock %}

cats/templates/cats/cats_form.html
{% extends 'cats/home.html' %}

{% block title %}Cats{% endblock %}

{% block content %}
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>
{% endblock %}

cats/templates/cats/cats_list.html
{% extends 'cats/home.html' %}

{% block title %}Cats{% endblock %}

{% block content %}
<h1>Cats</h1>
<ul>
    {% for cats in object_list %}
    <li>{{ cats.name }}  ({{ cats.date }} )
    <a href="{% url 'cats:cats_edit' cats.id %}">edit</a>
    <a href="{% url 'cats:cats_delete' cats.id %}">delete</a>
    </li>
    {% endfor %}
</ul>

<a href="{% url 'cats:cats_new' %}">New</a>
{% endblock %}

cats/templates/cats/home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

	<meta http-equiv="cache-control" content="max-age=0" />
	<meta http-equiv="cache-control" content="no-cache" />
	<meta http-equiv="expires" content="0" />
	<meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT" />
	<meta http-equiv="pragma" content="no-cache" />

    <title></title>

    <!-- Bootstrap Core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

</head>

<body id="baseBody">
    <div class="row">
        <div id="loader-background">
            <div id="loader-wrapper">
                <div id="loader"></div>
            </div>
        </div>
    </div>

    <div id="wrapper">
        <!-- Page Content -->
        <div id="content" class="container-fluid">
            <!-- Main content block -->
            <main role="main">
                {% block content %}{% endblock %}
            </main>

        </div>

    </div>

</body>

</html>

cats/templates/cats/menu.html
{% extends 'cats/home.html' %}

{% block title %}Home{% endblock %}

{% block content %}
    <h1>Dogs and Cats Test App</h1>
    <a href="/dogs/">Dogs</a><br>
    <a href="/cats/">Cats</a><br>
    <a href="/owners/">Owners</a><br>
{% endblock %}

dogs/templates/dogs/dogs_confirm_delete.html
<form method="post">{% csrf_token %}
    Are you sure you want to delete  ?
    <input type="submit" value="Submit" />
</form>

dogs/templates/dogs/dogs_form.html
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>

dogs/templates/dogs/dogs_list.html
<h1>dogs</h1>
<ul>
    {% for dogs in object_list %}
    <li>{{ dogs.name }}  ({{ dogs.date }} )
    <a href="{% url 'dogs:dogs_edit' dogs.id %}">edit</a>
    <a href="{% url 'dogs:dogs_delete' dogs.id %}">delete</a>
    </li>
    {% endfor %}
</ul>

<a href="{% url 'dogs:dogs_new' %}">New</a>

owners/templates/owners/owners_confirm_delete.html
<form method="post">{% csrf_token %}
    Are you sure you want to delete ?
    <input type="submit" value="Submit" />
</form>

owners/templates/owners/owners_form.html
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>

owners/templates/owners/owners_list.html
<h1>Owners</h1>
<ul>
    {% for owners in object_list %}
    <li>{{ owners.name }}  ({{ owners.date }} )
    <a href="{% url 'owners:owners_edit' owners.id %}">edit</a>
    <a href="{% url 'owners:owners_delete' owners.id %}">delete</a>
    </li>
    {% endfor %}
</ul>

<a href="{% url 'owners:owners_new' %}">New</a>